[project]
name = "ehragent"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "litellm>=1.97.0",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "pypdf>=6.16.2",
    "python-dotenv>=1.2.3",
    "python-levenshtein>=0.27.4",
    "pyyaml>=6.0.3",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
